### ISSUE TITLE
Capture in non-stop manner into ping-pong buffer ?

### ISSUE THREAD

**Issue by hieuhotxac** [pgmmpk/beaglebone_pru_adc#11]
I try to implement the method in your library to do that.
How can you transfer the value from ADC to buffer on ram ?

I have reading some documents for weeks, but still not coding yet. Can you help me a little?

**Comment by pgmmpk** [comment]
Have you figured this out?

If I remember correctly, this requires co-operation between Assembly PRU code and C code.

Current code does this:
1. PRU writes to the RAM buffer
2. when buffer is filled out, it raises interrupt and halts
3. C library waits for interrupt. When detected, it clears interrupt, then reads RAM and unpacks as Python array

You will need to modify it to have two (or more) buffers in RAM. At step (2) PRU should not halt, but
instead switch to writing to the other buffer.

Watch for buffer overrun conditions. It is possible that Python code takes too much time to process the buffer and by the time PRU wants to write to it it is still in-use by Python.

Good luck

**Comment by pgmmpk** [comment]
A separate project implements streaming ADC capture, see:
https://github.com/pgmmpk/bbb_pru_adc
