### ISSUE TITLE
Code for BBB wireless

### ISSUE THREAD

**Issue by TjebbeVQ** [pgmmpk/beaglebone_pru_adc#13]
Hello,

I would like to run this code on the beaglebone wireless. The problem is that the paths are not correct.
I tried adjusting the path from /sys/devices to /sys/devices/platform (where the capemgr is located), but this is followed a problem with the slots.
Can u help me Please?

Thank you in advance

**Comment by pgmmpk** [comment]
Code in this repository works only with kernel 3.8.13 and Angstrom linux.

My guess is that on BB wireless you are using different distro (not Angstrom?) and/or different kernel version. Another concern is that your hardware is different, meaning that BBB cape may not be compatible with BBW cape.

Unfortunately, I am not an expert on capes and can not help porting BBB cape to BBW system. I suggest you look at hardware forums for the help using ADC capture.
