### ISSUE TITLE
Slower sampling rate for oscilloscope mode

### ISSUE THREAD

**Issue by ashishkrbit** [pgmmpk/beaglebone_pru_adc#14]
Hi Mike
I am somehow not able to control my sampling rate where I need just 10,000 samples for a interval of 10 seconds (1 mico-second ) sampling rate on AIN0. I have posted the question on stackoverflow as well (https://stackoverflow.com/questions/47955289/analog-sampling-using-libpru-over-beaglebone).

A small hint of how shall I proceed would be greatly appreciated.

Thanks
Ashish

**Comment by pgmmpk** [comment]
A separate project implements streaming ADC capture, see:
https://github.com/pgmmpk/bbb_pru_adc
