### ISSUE TITLE
2018 Debian BBB - Apparent problem with slots.

### ISSUE THREAD

**Issue by jamesrobertparker** [pgmmpk/beaglebone_pru_adc#15]
All appears to install, but on  execution I get:

file "/usr/local/lib/python2.7/dist-packages/beaglebone_pru_adc-0.0.3-py2.7-linux-armv7l.egg/beaglebone_pru_adc/__init__.py", line 11 in <module>
SLOTS = glob.glob('sys/devices/bone_capemgr.*/slots')[0]
Indexerror: list index out of range.

I am aware that things have changed relatively recently with respect to 'slots' . Indeed, I could not get Adafruit_BBIO to work properly either. Is my system too new, or is the configuration on my system wrong?

[going crazy here - most posts on ADC are a few years onlder than my system]

**Comment by pgmmpk** [comment]
Hi James,

Sounds like you are using Debian. This software is for [Angstrom Linux](http://www.angstrom-distribution.org/). 

-Mike

**Comment by simiansinspace** [comment]
@pgmmpk do you have any plans to update this for Debian? This would be really useful for folks out there with newer boards running Debian!

**Comment by pgmmpk** [comment]
@simiansinspace - no plans for the Debian. Can you install recent Angstrom instead and check if thing works?

I am bit confused by the reference to the "newer boards". BBB did not have hardware revisions after rev C, right?

**Comment by jamesrobertparker** [comment]
In fact, what I did is install an older version of Debian. It still failed, but on a whim I ran the code as SU on the older version, and it appears to work.

Angstrom is fairly old and I worried about support, updates. I have it on a uSD but have not used it.

**Comment by pgmmpk** [comment]
@jamesrobertparker - thank you for experimenting. I guess cape it still the same and device tree did not change Angstrom vs Debian. These are good news.

1. Since it was file permissions issue (at least on the older Debian), maybe it will work using "sudo" in the latest Debian?
2. Angstrom distro seem to be alive, I am seeing updates made this year https://dominion.thruhere.net/angstrom/nightlies/

**Comment by simiansinspace** [comment]
Interesting, @jamesrobertparker I tried to run it with sudo and have the same issue as you with "index of out range"

`debian@beaglebone:~/beaglebone_pru_adc/examples$ sudo python ./basic.py
Traceback (most recent call last):
  File "./basic.py", line 1, in <module>
    import beaglebone_pru_adc as adc
  File "/usr/local/lib/python2.7/dist-packages/beaglebone_pru_adc-0.0.3-py2.7-linux-armv7l.egg/beaglebone_pru_adc/__init__.py", line 11, in <module>
    SLOTS = glob.glob('/sys/devices/bone_capemgr.*/slots')[0]
IndexError: list index out of range`

`debian@beaglebone:~/beaglebone_pru_adc/examples$ uname -a                           
Linux beaglebone 4.4.30-ti-r64 #1 SMP Fri Nov 4 21:23:33 UTC 2016 armv7l GNU/Linux `

Any ideas?

**Comment by pgmmpk** [comment]
@simiansinspace does the path exist on your device?

**Comment by jamesrobertparker** [comment]
Which path, specifically?

Withe the older Debian and running as root things seemed to work OK.

**Comment by pgmmpk** [comment]
@simiansinspace `/sys/devices/bone_capemgr.*` and sub-paths `slots`. 

Cape device handlers are mapped to device files... Maybe newer Debian uses newer kernel where device tree was changed...

**Comment by simiansinspace** [comment]
You are correct @pgmmpk , the slots file has disappeared on the Debian release, for various reasons below:
https://elinux.org/Beagleboard:BeagleBoneBlack_Debian#Where_did_the_slots_file_go.3F
