### ISSUE TITLE
capture.times and capture.values gives unexpected counts

### ISSUE THREAD

**Issue by mtkaplanoglu** [pgmmpk/beaglebone_pru_adc#17]
Dear, 

  We're using "beaglebone_pru_adc" code to measure 50/60 Hz sinusoidal signals for different amplitudes between (0 - 1.8 Volts). But capture.values gives unexpected values periodically. I've examined the output and tried to figure out the real issue. 

When i measure capture.times for 0.01 second periodically gives unexpected ticks as output, also ADC gives unexpected results at same time. 

In the following screenshot, 1d plot for captured.times (ticks) shown 
https://prnt.sc/ptm7yz

Following code used to observe the situation 

`
import beaglebone_pru_adc as adc
import time

while True:
  capture = adc.Capture()
  capture.start()
  t0 = time.time()

  while (time.time()-t0 < 0.001):
          a = 1 # just for waiting.

  print capture.timer

  capture.stop() 
  capture.wait() 
  capture.close() 
`

I've used it for different boards and gives same result, (even there is no any ADC input or grounded). Tested on : Linux beaglebone 3.8.13-xenomai-r83 

Regards,

**Comment by mtkaplanoglu** [comment]
Unexpected tick counts repeating continuously 
https://prnt.sc/ptpc2g

**Comment by pgmmpk** [comment]
Help me to understand the chart. What are the axis there? And what is the expected behavior?

-Mike

**Comment by mtkaplanoglu** [comment]
> Help me to understand the chart. What are the axis there? And what is the expected behavior?
> 
> -Mike

Dear Mike, thank you for your answer.

I expect to see a straight line, because im observing ticks counted between a constant time interval (about 0.001 seconds). However, somehow capture.timer gives relatively high counts periodically. First, i suspected time.time() function is not accurate but when i examine and compare results capture.timer and capture.values for continuous AC signal, captured values is absolutely not seems like AC form while capture.timer gives high counted ticks.

x axis is just iteration, y axis is capture.timer output. I've changed ema_pow and delay but the behaviour is not changing. The point is that this behaviour is repeating for a period.

https://prnt.sc/ptpc2g

**Comment by pgmmpk** [comment]
hmm. Could it be that at these times CPU is getting busy with some other tasks and actual time interval is not 0.001, but much higher?

How about logging not only the tick count, but also the actual time interval, like this:
```python
import beaglebone_pru_adc as adc
import time

capture = adc.Capture()
capture.start()

old_time = time.time()
old_ticks = capture.timer()

while True:
    time.sleep(0.001)
    new_time = time.time()
    new_ticks = capture.ticks
    elapsed_time = new_time - old_time
    elapsed_ticks = new_ticks - old_ticks
    print elapsed_time, elapsed_ticks
    old_time = new_time
    old_ticks = new_ticks

capture.stop()
capture.wait()
capture.close()
```

**Comment by mtkaplanoglu** [comment]
Dear Mike,

The output is : 
https://prnt.sc/pu2cho

So, you're correct CPU comes %100 at the point. Is there a way to overcome the issue? For example: can i accumulate capture.values (for all ADC ports) and read it every 20ms ? I dont need high sampling rates, just precise timing.


Thanks, regards.
Tevfik

**Comment by pgmmpk** [comment]
Do I understand correctly that you need precise timing of the measurement? If yes, here are some options:
1. Find out where the CPU spikes come from (what other tasks are running? or maybe Python garbage collector kicks in?). And eliminate them. This can help to a certain extend. But due to the nature of linux task scheduling mechanism (not real-time), some deviations are still expected.
2. Look at [oscilloscope](https://github.com/pgmmpk/beaglebone_pru_adc/blob/master/examples/oscilloscope.py) mode, that measures the value and buffers it at PRU side - this gives you very precise timings. Downsides is: only one value can be measured (limitation of my implementation).
3. Write new PRU code that does precisely what you need (painful).

**Comment by mtkaplanoglu** [comment]
- I've changed time.sleep() to a more reliable algorithm to decrease CPU usage, there is no other process except OS itself. CPU usage is not higher than ~%60 while the code is working. Also, im running it with "nice -n -20" for highest priority.

And i again capture data, the result is :
https://prnt.sc/pu71l6
(normal data at bottom, strange two at top)
im sure that AC source is correct. 

- Oscilloscope mode is unfortunately does not fit on my application.

The last option seems as the correct way..

**Comment by pgmmpk** [comment]
If your task is to capture the correct shape (the sine for example), then small deviations in actual capture time should not matter. You just take this into account. Take the reading of time.time() at the same time that you take the reading of the value, then plot this as (X,Y). 

> I've changed time.sleep() to a more reliable algorithm to decrease CPU usage

Out of curiosity, what is this algorithm? `time.sleep()` does not use CPU at all, AFAIK

> Also, im running it with "nice -n -20" for highest priority.

Negative `nice` value lowers process scheduling priority. Looks like you set it for the *lowest* priority.

> CPU usage is not higher than ~%60 while the code is working

This is super high for a program that mostly sleeps (unless sleep time is zero or very close to zero).

**Comment by mtkaplanoglu** [comment]
Dear Mike,

I'm adding my answers between the lines.

> If your task is to capture the correct shape (the sine for example), then small deviations in actual capture time should not matter. You just take this into account. Take the reading of time.time() at the same time that you take the reading of the value, then plot this as (X,Y).
In my application i have to capture every period of waveform to compute amplitude with minimum %99 accuracy, DFT or RMS calculations it makes sense.
> 
> > I've changed time.sleep() to a more reliable algorithm to decrease CPU usage
> 
> Out of curiosity, what is this algorithm? `time.sleep()` does not use CPU at all, AFAIK
> 
If sleep value less than 0.001 seconds, its not behave reliable. To following function makes it accurate and decrease CPU usage.

    from time import time, sleep


    def sleep_min(delay):
      accum = 0
      remainder = delay

      while accum < delay:
          begin = time()
          sleep(remainder)
          end = time()
          slept = end - begin
          accum += slept
          remainder -= slept`

> > Also, im running it with "nice -n -20" for highest priority.
> 
> Negative `nice` value lowers process scheduling priority. Looks like you set it for the _lowest_ priority.

can there be a mistake ? 
_NI  --  Nice value
      The nice value of the task.  A negative nice value means higher  priority,
      whereas  a  positive  nice value means lower priority.  Zero in this field
      simply means priority will not be adjusted in determining  a  task’s  dis-
      patchability._

> 
> > CPU usage is not higher than ~%60 while the code is working
> 
> This is super high for a program that mostly sleeps (unless sleep time is zero or very close to zero).

Unfortunately yes. 

Also, what do you think about buffering PRU output like FIFO in RAM? 

Thanks, regards,
Tevfik

**Comment by pgmmpk** [comment]
1. Code is strange as it does not do anything at all. Test it and fix it, please. I think you are attempting to compensate for the non-zero processing time around sleep?
2. Yes, lower nice has higher priority - my mistake!

I think you should do this:
1. measure how fast process switching is in your kernel. It can be as slow as > 10ms . You may be able to fiddle with kernel params or recompile kernel to improve that. Remove any capture code and just run a loop with 1ms sleep and check the actual timings. This will give you your hardware/os limits on time resolution using CPU timers. While there, measure the jitter. If unacceptable, you have no choice but switch to PRU programming.
2. If acceptable, make sure that you *do not* assume that X (time) values captured are equidistant, but measure the actual times, and draw your pictures accordingly.

And, please, close this issue as this has nothing to do with the driver. You can e-mail me directly (see my profile for the e-mail)

**Comment by mtkaplanoglu** [comment]
Dear Mike, 

Instead of changing nice but changing priority using chrt solved the issue, thanks for your recommendations. 

Regards,
