### ISSUE TITLE
Code modification

### ISSUE THREAD

**Issue by alanxuefei** [pgmmpk/beaglebone_pru_adc#4]
Hi Mike 
  I am trying to implement the continuous ADC.

First,  I run the MAKE to generate the firmware.bin file.
Then，I run python setup.py install to load the firmware.bin

However, all ADCs become  0000000

Could you give any tips for compilation and code loader?

Thanks in advance
Fei

**Comment by ItsMeMegaMind** [comment]
Hi alanxuefei

I am also currently working on continuous ADC and was trying to make it work with your code. The problem is I am using new beaglebone black wireless running debian. Is this code compatible with beaglebone black wireless?

**Comment by pgmmpk** [comment]
A separate project implements streaming ADC capture, see:
https://github.com/pgmmpk/bbb_pru_adc
