### ISSUE TITLE
Python Path

### ISSUE THREAD

**Issue by martykube** [pgmmpk/beaglebone_pru_adc#6]
Hi Mike,

I've been running qb_server.py.  I'm calibrating the wheel encoders.  When I calibrated the encoders with the v1 client code (non-PRU) they were off by 40% over a straight 3m drive.   The signals dumped from the PRU looked way better.  I'll let you know how it pans out.

I'm no python expert, I've been picking it up as I go.  One problem I have is this:

```
<quickbot_api> hostname
beaglebone
<quickbot_api> python -V
Python 2.7.3
<quickbot_api> sudo python tools/calibrate_wheel_encoders.py 
Traceback (most recent call last):
  File "tools/calibrate_wheel_encoders.py", line 3, in <module>
    import config
ImportError: No module named config
<quickbot_api> ls
config.py  config.pyc  qb_client.py  qb.py  qb.pyc  qb_server.py  qb_simple_behavior.py  README.md  research  robot  tools

```

I'm sure there is a way to wrangle the paths... Any suggestions?

Thanks,
Marty

**Comment by pgmmpk** [comment]
Looks like you did not install package. To make it work without installing
(recommended) just do this:

export PYTHONPATH=.

This adds current directory to python path.

Hope this helps
-Mike

**Comment by martykube** [comment]
Thanks!
