### ISSUE TITLE
Capture mutiple ADC channels in oscilloscope mode

### ISSUE THREAD

**Issue by tn0432** [pgmmpk/beaglebone_pru_adc#9]
Hello!

I am trying to use 4 ADC channels to record the 25kHZ signal. So I think the ADC capture settting in oscilloscope mode is more suitable for my purpose. So far, I see that it is only available for 1 channel.

Is there any available function in your librabry can do the job? 

Thanks

**Comment by pgmmpk** [comment]
Hi,

Unfortunately, only one channel can be captured in oscilloscope mode.

To capture more than one value one have to change the PRU assembly code.

**Comment by kzoltaan** [comment]
can u help me in this modification?

**Comment by pgmmpk** [comment]
If you have a concrete question regarding the current code, sure, I can answer it. May not be able to provide answers to the open-ended questions or to provide general guidance. Good luck!

**Comment by pgmmpk** [comment]
A separate project implements streaming ADC capture, see:
https://github.com/pgmmpk/bbb_pru_adc
